# Port Ayarı
server.port=8585

# Spring DevTools Otomatik Yeniden Başlatma Ayarı
spring.devtools.restart.enabled=true

# Özel Değerler (@Value ile çağrılacak)
course.name=Java Spring Boot
project.developer.fullname=Yağız Uçar